
package ec.edu.ups.servicios;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-23T21:46:56.442-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class CajeroServiceSOAP_CajeroServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servicios.ProyectoFinal.appdis/", "CajeroServiceSOAPService");

    private CajeroServiceSOAP_CajeroServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CajeroServiceSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CajeroServiceSOAPService ss = new CajeroServiceSOAPService(wsdlURL, SERVICE_NAME);
        CajeroServiceSOAP port = ss.getCajeroServiceSOAPPort();  
        
        {
        System.out.println("Invoking deposito...");
        java.lang.String _deposito_arg0 = "";
        double _deposito_arg1 = 0.0;
        ec.edu.ups.servicios.Cuenta _deposito_arg2 = null;
        java.lang.String _deposito__return = port.deposito(_deposito_arg0, _deposito_arg1, _deposito_arg2);
        System.out.println("deposito.result=" + _deposito__return);


        }
        {
        System.out.println("Invoking retiro...");
        java.lang.String _retiro_arg0 = "";
        double _retiro_arg1 = 0.0;
        ec.edu.ups.servicios.Cuenta _retiro_arg2 = null;
        java.lang.String _retiro__return = port.retiro(_retiro_arg0, _retiro_arg1, _retiro_arg2);
        System.out.println("retiro.result=" + _retiro__return);


        }
        {
        System.out.println("Invoking obtenerDatosCuenta...");
        java.lang.String _obtenerDatosCuenta_arg0 = "";
        ec.edu.ups.servicios.Cuenta _obtenerDatosCuenta__return = port.obtenerDatosCuenta(_obtenerDatosCuenta_arg0);
        System.out.println("obtenerDatosCuenta.result=" + _obtenerDatosCuenta__return);


        }

        System.exit(0);
    }

}
