package ec.edu.ups.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-23T23:40:38.160-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://servicios.ProyectoFinal.appdis/", name = "CajeroServiceSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface CajeroServiceSOAP {

    @WebMethod(operationName = "Deposito")
    @RequestWrapper(localName = "Deposito", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.Deposito")
    @ResponseWrapper(localName = "DepositoResponse", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.DepositoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String deposito(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ec.edu.ups.servicios.Cuenta arg2
    );

    @WebMethod(operationName = "Retiro")
    @RequestWrapper(localName = "Retiro", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.Retiro")
    @ResponseWrapper(localName = "RetiroResponse", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.RetiroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String retiro(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        ec.edu.ups.servicios.Cuenta arg2
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerDatosCuenta", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.ObtenerDatosCuenta")
    @ResponseWrapper(localName = "obtenerDatosCuentaResponse", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.ObtenerDatosCuentaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ec.edu.ups.servicios.Cuenta obtenerDatosCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "tranferirDineroCuenta", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.TranferirDineroCuenta")
    @ResponseWrapper(localName = "tranferirDineroCuentaResponse", targetNamespace = "http://servicios.ProyectoFinal.appdis/", className = "ec.edu.ups.servicios.TranferirDineroCuentaResponse")
    public void tranferirDineroCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.servicios.Cuenta arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ec.edu.ups.servicios.Cuenta arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3
    );
}
